// File generated from our OpenAPI spec by Stainless.

package com.swarms.api.models.agent.batch

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.swarms.api.core.ExcludeMissing
import com.swarms.api.core.JsonField
import com.swarms.api.core.JsonMissing
import com.swarms.api.core.JsonValue
import com.swarms.api.errors.SwarmsClientInvalidDataException
import java.util.Collections
import java.util.Objects
import java.util.Optional
import kotlin.jvm.optionals.getOrNull

class BatchRunResponse
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val batchId: JsonField<String>,
    private val executionTime: JsonField<Double>,
    private val results: JsonValue,
    private val timestamp: JsonField<String>,
    private val totalRequests: JsonField<Long>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("batch_id") @ExcludeMissing batchId: JsonField<String> = JsonMissing.of(),
        @JsonProperty("execution_time")
        @ExcludeMissing
        executionTime: JsonField<Double> = JsonMissing.of(),
        @JsonProperty("results") @ExcludeMissing results: JsonValue = JsonMissing.of(),
        @JsonProperty("timestamp") @ExcludeMissing timestamp: JsonField<String> = JsonMissing.of(),
        @JsonProperty("total_requests")
        @ExcludeMissing
        totalRequests: JsonField<Long> = JsonMissing.of(),
    ) : this(batchId, executionTime, results, timestamp, totalRequests, mutableMapOf())

    /**
     * The unique identifier for the agent batch completion.
     *
     * @throws SwarmsClientInvalidDataException if the JSON field has an unexpected type (e.g. if
     *   the server responded with an unexpected value).
     */
    fun batchId(): Optional<String> = batchId.getOptional("batch_id")

    /**
     * The execution time of the agent batch completion.
     *
     * @throws SwarmsClientInvalidDataException if the JSON field has an unexpected type (e.g. if
     *   the server responded with an unexpected value).
     */
    fun executionTime(): Optional<Double> = executionTime.getOptional("execution_time")

    /**
     * The outputs generated by the agent.
     *
     * This arbitrary value can be deserialized into a custom type using the `convert` method:
     * ```java
     * MyClass myObject = batchRunResponse.results().convert(MyClass.class);
     * ```
     */
    @JsonProperty("results") @ExcludeMissing fun _results(): JsonValue = results

    /**
     * The timestamp when the agent batch completion was created.
     *
     * @throws SwarmsClientInvalidDataException if the JSON field has an unexpected type (e.g. if
     *   the server responded with an unexpected value).
     */
    fun timestamp(): Optional<String> = timestamp.getOptional("timestamp")

    /**
     * The total number of requests in the batch.
     *
     * @throws SwarmsClientInvalidDataException if the JSON field has an unexpected type (e.g. if
     *   the server responded with an unexpected value).
     */
    fun totalRequests(): Optional<Long> = totalRequests.getOptional("total_requests")

    /**
     * Returns the raw JSON value of [batchId].
     *
     * Unlike [batchId], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("batch_id") @ExcludeMissing fun _batchId(): JsonField<String> = batchId

    /**
     * Returns the raw JSON value of [executionTime].
     *
     * Unlike [executionTime], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("execution_time")
    @ExcludeMissing
    fun _executionTime(): JsonField<Double> = executionTime

    /**
     * Returns the raw JSON value of [timestamp].
     *
     * Unlike [timestamp], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("timestamp") @ExcludeMissing fun _timestamp(): JsonField<String> = timestamp

    /**
     * Returns the raw JSON value of [totalRequests].
     *
     * Unlike [totalRequests], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("total_requests")
    @ExcludeMissing
    fun _totalRequests(): JsonField<Long> = totalRequests

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /** Returns a mutable builder for constructing an instance of [BatchRunResponse]. */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [BatchRunResponse]. */
    class Builder internal constructor() {

        private var batchId: JsonField<String> = JsonMissing.of()
        private var executionTime: JsonField<Double> = JsonMissing.of()
        private var results: JsonValue = JsonMissing.of()
        private var timestamp: JsonField<String> = JsonMissing.of()
        private var totalRequests: JsonField<Long> = JsonMissing.of()
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        @JvmSynthetic
        internal fun from(batchRunResponse: BatchRunResponse) = apply {
            batchId = batchRunResponse.batchId
            executionTime = batchRunResponse.executionTime
            results = batchRunResponse.results
            timestamp = batchRunResponse.timestamp
            totalRequests = batchRunResponse.totalRequests
            additionalProperties = batchRunResponse.additionalProperties.toMutableMap()
        }

        /** The unique identifier for the agent batch completion. */
        fun batchId(batchId: String?) = batchId(JsonField.ofNullable(batchId))

        /** Alias for calling [Builder.batchId] with `batchId.orElse(null)`. */
        fun batchId(batchId: Optional<String>) = batchId(batchId.getOrNull())

        /**
         * Sets [Builder.batchId] to an arbitrary JSON value.
         *
         * You should usually call [Builder.batchId] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun batchId(batchId: JsonField<String>) = apply { this.batchId = batchId }

        /** The execution time of the agent batch completion. */
        fun executionTime(executionTime: Double?) =
            executionTime(JsonField.ofNullable(executionTime))

        /**
         * Alias for [Builder.executionTime].
         *
         * This unboxed primitive overload exists for backwards compatibility.
         */
        fun executionTime(executionTime: Double) = executionTime(executionTime as Double?)

        /** Alias for calling [Builder.executionTime] with `executionTime.orElse(null)`. */
        fun executionTime(executionTime: Optional<Double>) =
            executionTime(executionTime.getOrNull())

        /**
         * Sets [Builder.executionTime] to an arbitrary JSON value.
         *
         * You should usually call [Builder.executionTime] with a well-typed [Double] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun executionTime(executionTime: JsonField<Double>) = apply {
            this.executionTime = executionTime
        }

        /** The outputs generated by the agent. */
        fun results(results: JsonValue) = apply { this.results = results }

        /** The timestamp when the agent batch completion was created. */
        fun timestamp(timestamp: String?) = timestamp(JsonField.ofNullable(timestamp))

        /** Alias for calling [Builder.timestamp] with `timestamp.orElse(null)`. */
        fun timestamp(timestamp: Optional<String>) = timestamp(timestamp.getOrNull())

        /**
         * Sets [Builder.timestamp] to an arbitrary JSON value.
         *
         * You should usually call [Builder.timestamp] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun timestamp(timestamp: JsonField<String>) = apply { this.timestamp = timestamp }

        /** The total number of requests in the batch. */
        fun totalRequests(totalRequests: Long?) = totalRequests(JsonField.ofNullable(totalRequests))

        /**
         * Alias for [Builder.totalRequests].
         *
         * This unboxed primitive overload exists for backwards compatibility.
         */
        fun totalRequests(totalRequests: Long) = totalRequests(totalRequests as Long?)

        /** Alias for calling [Builder.totalRequests] with `totalRequests.orElse(null)`. */
        fun totalRequests(totalRequests: Optional<Long>) = totalRequests(totalRequests.getOrNull())

        /**
         * Sets [Builder.totalRequests] to an arbitrary JSON value.
         *
         * You should usually call [Builder.totalRequests] with a well-typed [Long] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun totalRequests(totalRequests: JsonField<Long>) = apply {
            this.totalRequests = totalRequests
        }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [BatchRunResponse].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         */
        fun build(): BatchRunResponse =
            BatchRunResponse(
                batchId,
                executionTime,
                results,
                timestamp,
                totalRequests,
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    fun validate(): BatchRunResponse = apply {
        if (validated) {
            return@apply
        }

        batchId()
        executionTime()
        timestamp()
        totalRequests()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: SwarmsClientInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    @JvmSynthetic
    internal fun validity(): Int =
        (if (batchId.asKnown().isPresent) 1 else 0) +
            (if (executionTime.asKnown().isPresent) 1 else 0) +
            (if (timestamp.asKnown().isPresent) 1 else 0) +
            (if (totalRequests.asKnown().isPresent) 1 else 0)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is BatchRunResponse &&
            batchId == other.batchId &&
            executionTime == other.executionTime &&
            results == other.results &&
            timestamp == other.timestamp &&
            totalRequests == other.totalRequests &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(
            batchId,
            executionTime,
            results,
            timestamp,
            totalRequests,
            additionalProperties,
        )
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "BatchRunResponse{batchId=$batchId, executionTime=$executionTime, results=$results, timestamp=$timestamp, totalRequests=$totalRequests, additionalProperties=$additionalProperties}"
}
